// src/app/experience/page.tsx
import styles from './experience.module.css';

export default function Experience() {
  return (
    <section className={styles.timeline} id="section2">
      <h3 className="heading">Experiencia</h3>
      <div className={styles.timeline_title}>
        <h4>NTT DATA</h4>
      </div>
      <div className={styles.timeline_items}>
        <div className={styles.timeline_item}>
          <div className={styles.timeline_dot}></div>
          <div className={styles.timeline_date}>2020 - 2021</div>
          <div className={styles.timeline_content}>
            <h3>Desarrollador Full-stack</h3>
            <p>
              He trabajado en la creación de un aplicativo web llamado New LDI, 
              el cual sirve para toda la gestión de los clientes de larga distancia y del Carrier 188 y 181.
            </p>
          </div>
        </div>
        <div className={styles.timeline_item}>
          <div className={styles.timeline_dot}></div>
          <div className={styles.timeline_date}>2022</div>
          <div className={styles.timeline_content}>
            <h3>Desarrollador Mobile</h3>
            <p>
              He trabajado en el mantenimiento de una aplicación móvil llamada App Delivery, 
              la cual sirve para que los despachadores de equipos móviles puedan gestionar las entregas.
            </p>
          </div>
        </div>
        <div className={styles.timeline_item}>
          <div className={styles.timeline_dot}></div>
          <div className={styles.timeline_date}>2023</div>
          <div className={styles.timeline_content}>
            <h3>Desarrollador Full-stack</h3>
            <p>
              He trabajado en el desarrollo un aplicativo web llamado Resolutor Web, 
              que sirve para poder gestionar los reclamos de la atención al cliente de Movistar TV.
            </p>
          </div>
        </div>
        <div className={styles.timeline_item}>
          <div className={styles.timeline_dot}></div>
          <div className={styles.timeline_date}>2023 - 2025</div>
          <div className={styles.timeline_content}>
            <h3>Desarrollador Full-stack</h3>
            <p>
            Estoy trabajando en el mantenimiento de un aplicativo llamado Registro MTV, 
            el cual sirve para que un cliente pueda registrarse y activar el servicio Movistar TV.
            </p>
          </div>
        </div>
      </div>
      <div className={styles.timeline_title}>
        <h4>ENTELGY</h4>
      </div>
      <div className={styles.timeline_item}>
        <div className={styles.timeline_dot}></div>
        <div className={styles.timeline_date}>2025 - Actualidad</div>
        <div className={styles.timeline_content}>
          <h3>Desarrollador Full-stack</h3>
          <p>
          Estoy trabajando en la migracion y refacotrizacion de un aplicativo web llamado SIAPER, 
          perteneciente a la Contraloria General de la Republica de Chile.
          </p>
        </div>
      </div>
    </section>
  );
}

// angular/src/app/components/experience/experience.component.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';

@Component({
  selector: 'app-experience',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './experience.component.html',
  styleUrl: './experience.component.scss'
})
export class ExperienceComponent {

}

<section id="section2">
    <h3 class="heading">Experiencia</h3>
    
    <div class="timeline-title">
        <h4>NTT DATA</h4>
    </div>
    <div class="timeline-items">
        <div class="timeline-item">
            <div class="timeline-dot"></div>
            <div class="timeline-date">2020 - 2022</div>
            <div class="timeline-content">
                <h3>Desarrollador Full-stack</h3>
                <p>
                He trabajado en la creación de un aplicativo web llamado “New LDI”, 
                el cual sirve para toda la gestión de los clientes de larga distancia y del Carrier 188 y 181.
                </p>
            </div>
        </div>
        <div class="timeline-item">
            <div class="timeline-dot"></div>
            <div class="timeline-date">2021</div>
            <div class="timeline-content">
            <h3>Desarrollador Mobile</h3>
            <p>
                He trabajado en el mantenimiento de una aplicación movil de llamada “App Delivery”, 
                el cual sirve para que los despachadores de quipos moviles puedan gestionar las entregas. 
            </p>
            </div>
        </div>
        <div class="timeline-item">
            <div class="timeline-dot"></div>
            <div class="timeline-date">2023</div>
            <div class="timeline-content">
            <h3>Desarrollador Full-stack</h3>
            <p>
                He trabajado en el desarrollo un aplicativo web llamado "Resolutor Web", 
                que sirve para poder gestionar los reclamos de la atención al cliente de Movistar TV.
            </p>
            </div>
        </div>
        <div class="timeline-item">
            <div class="timeline-dot"></div>
            <div class="timeline-date">2023 - Actualmente</div>
            <div class="timeline-content">
            <h3>Desarrollador Full-stack</h3>
            <p>
                Estoy trabajando en el mantenimiento de un aplicativo de llamado “Registro MTV”, 
                el cual sirve para que un cliente pueda registrarse y activar el servicio Movistar TV. 
            </p>
            </div>
        </div>
    </div>
</section>
