// src/app/home/page.tsx

import Links from '../components/links/Links';
import styles from './home.module.css';

export default function Home() {
  return (
    <section className={styles.home} id="section1">
      <div className={styles.title_content}>
        <h1>Felipe Alarcón Contreras</h1>
        <div className={styles.typing_content}>
          <h3 className={styles.typing_text}>Desarrollador Web</h3>
        </div>
      </div>
      <div className={styles.description_content}>
        Tengo 5 años de experiencia en el campo del desarrollo
        de software, donde he colaborado con clientes de
        diversos sectores. Tengo experiencia utilizando diversas tecnologías
        de front-end, back-end, bases de datos, herramientas DevOps y
        metodologías ágiles como SCRUM.  
      </div>
      <Links />
    </section>
  );
}

// angular/src/app/components/home/home.component.ts
import { Component, OnInit } from '@angular/core';
import { ExperienceComponent } from '../experience/experience.component';
import { ActivatedRoute } from '@angular/router';
import { EducationComponent } from "../education/education.component";
import { SkillsComponent } from '../skills/skills.component';

@Component({
  selector: 'app-home',
  standalone: true,
  imports: [ExperienceComponent, EducationComponent, SkillsComponent],
  templateUrl: './home.component.html',
  styleUrl: './home.component.scss'
})
export class HomeComponent implements OnInit {

  constructor(private route: ActivatedRoute) { }

  ngOnInit(): void {
    this.route.fragment.subscribe(fragment => {
      if (fragment) {
        const element = document.getElementById(fragment);
        if (element) {
          element.scrollIntoView({ behavior: 'smooth' });
        }
      }
    });
  }

  redirectWindow(page: string) {
    switch(page) {
      case 'linkedin':
        window.open('https://linkedin.com/in/felipe-ignacio-alarcon-contreras-670a25286');
        break;
      case 'github':
        window.open('https://github.com/felipe1521');
        break;
    }
    
  }
}

<section class="home" id="section1">
    <div class="home-content">
        <h1>Hola, me llamo <br>Felipe Ignacio Alarcón Contreras</h1>
        <h3 class="text-animation">Soy un <span></span></h3>
        <br>
        <p>
            Soy un desarrollador Full Stack con 5 años de experiencia y actualmente trabajo en NTT DATA, donde he colaborado con clientes de diversos sectores.
            Tengo experiencia utilizando diversas tecnologías de front-end, back-end, bases de datos, herramientas DevOps y metodologías ágiles como SCRUM.
        </p>
        <div class="social-icons">
            <a href="#" (click)="redirectWindow('linkedin')"><i class='bx bxl-linkedin'></i></a>
            <a href="#" (click)="redirectWindow('github')"><i class='bx bxl-github'></i></a>
            <a href="#" (click)="redirectWindow('gmail')"><i class='bx bxl-gmail'></i></a>
            <a href="#" (click)="redirectWindow('whatsapp')"><i class='bx bxl-whatsapp'></i></a>
        </div>
        <!--<button class="btn">Contactar</button>-->
    </div>
</section>

<app-experience></app-experience>

<app-education></app-education>

<app-skills></app-skills>
