// src/app/education/page.jsx
import React from "react";
import "./module.css";

export default function Education() {
  return (
    <section className="education" id="section3">
      <h2 className="heading">Educación</h2>
      <div className="education-container">
        <div className="education-box">
          <div className="education-info">
            <h4>IP Santo Tomas</h4>
            <h5>Analista Programador (2017 - 2018)</h5>
            <p>
              Un analista programador es un profesional encargado de analizar,
              desarrollar y mantener sistemas de software, para lo que necesita
              contar con determinadas habilidades, entre las que se incluyen la
              programación y el desarrollo.
            </p>
          </div>
        </div>
        <div className="education-box">
          <div className="education-info">
            <h4>IP Santo Tomas</h4>
            <h5>Ingeniero Informático (2017 - 2021)</h5>
            <p>
              Un ingeniero en informática se encarga de diseñar y analizar los
              procesos y estructuras de software y hardware, que hacen posible
              el tratamiento y explotación de datos digitales.
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}

// src/app/components/education/education.component.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';

@Component({
  selector: 'app-education',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './education.component.html',
  styleUrl: './education.component.scss'
})
export class EducationComponent {

}

<section class="education" id="section3">
    <h2 class="heading">Educación</h2>
    <div class="education-container">
        <div class="education-box">
            <div class="education-info">
                <h4>IP Santo Tomas</h4>
                <h5>Analista Programador (2017 - 2018)</h5>
                <p>
                    Un analista programador es un profesional encargado de analizar, desarrollar y mantener 
                    sistemas de software, para lo que necesita contar con determinadas habilidades, 
                    entre las que se incluyen la programación y el desarrollo. 
                </p>
            </div>
        </div>
        <div class="education-box">
            <div class="education-info">
                <h4>IP Santo Tomas</h4>
                <h5>Ingeniero Informático (2017 - 2021)</h5>
                <p>
                    Un ingeniero en informática se encarga de diseñar y analizar los procesos y estructuras
                    de software y hardware, que hacen posible el tratamiento y explotación de datos digitales.
                </p>
            </div>
        </div>
    </div>
</section>
